apiVersion: v1
kind: Service
metadata:
  name: comunidades-service
  labels: { app.kubernetes.io/name: comunidades-service, app.kubernetes.io/component: service, app.kubernetes.io/part-of: 4life }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: comunidades-service }
  ports:
    - { name: http, port: 3002, targetPort: http }
