apiVersion: v1
kind: ConfigMap
metadata:
  name: doadores-service-config
  labels: { app.kubernetes.io/name: doadores-service, app.kubernetes.io/part-of: 4life }
data:
  PORT: "3001"
  LOG_LEVEL: info
  DB_HOST: doadores-db
  DB_PORT: "5432"
  DB_NAME: doadores
  DB_USER: doadores
