apiVersion: v1
kind: Service
metadata:
  name: bff-mobile
  labels: { app.kubernetes.io/name: bff-mobile, app.kubernetes.io/component: bff, app.kubernetes.io/part-of: 4life }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: bff-mobile }
  ports:
    - { name: http, port: 4001, targetPort: http }
